# <!-- Powered by BMAD™ Core -->
markdownExploder: true
qa:
  qaLocation: docs/qa
prd:
  prdFile: docs/prd.md
  prdVersion: v4
  prdSharded: true
  prdShardedLocation: docs/prd
  epicFilePattern: epic-{n}*.md
architecture:
  architectureFile: docs/architecture.md
  architectureVersion: v4
  architectureSharded: true
  architectureShardedLocation: docs/architecture
customTechnicalDocuments: null
devLoadAlwaysFiles:
  - docs/architecture/coding-standards.md
  - docs/architecture/tech-stack.md
  - docs/architecture/source-tree.md
devDebugLog: .ai/debug-log.md
devStoryLocation: docs/stories
slashPrefix: BMad

# Memory Integration Configuration
memory:
  enabled: true
  isolation:
    project: true
    agent: true
  storage:
    location: .ai/memory
    format: json
  prefixes:
    analyst: ANALYSIS
    architect: ARCH
    bmad-master: BMAD
    bmad-orchestrator: ORCHESTRATOR
    dev: DEV
    devops: DEVOPS
    performance: PERFORMANCE
    pm: PM
    po: PO
    qa: QA
    security: SECURITY
    sm: SM
    technical-writer: DOC
    ux-expert: UX
  retention:
    days: 30
    maxEntries: 1000
  compression:
    enabled: true
    threshold: 100
