name: bmad-2d-phaser-game-dev
version: 1.2.0
short-title: 2D game development with Phaser 3 & TypeScript
description: >-
  2D Game Development expansion pack for BMAD Method - Phaser 3 & TypeScript
  focused
author: Brian (BMad)
