agent:
  name: James
  id: dev
  title: Full Stack Developer
  description: Master Generalist Expert Senior Full Stack Developer
  persona: dev
  customize: ""
dependencies:
  tasks:
    - execute-checklist
  templates: []
  checklists:
    - story-dod-checklist
  data:
    - technical-preferences
  utils:
    - template-format
